/*

 PLAYER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PlayerTilesBank 0

/* Super Gameboy palette 0 */
#define PlayerTilesSGBPal0c0 30687
#define PlayerTilesSGBPal0c1 8935
#define PlayerTilesSGBPal0c2 6596
#define PlayerTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define PlayerTilesSGBPal1c0 30687
#define PlayerTilesSGBPal1c1 8935
#define PlayerTilesSGBPal1c2 6596
#define PlayerTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define PlayerTilesSGBPal2c0 30687
#define PlayerTilesSGBPal2c1 8935
#define PlayerTilesSGBPal2c2 6596
#define PlayerTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define PlayerTilesSGBPal3c0 30687
#define PlayerTilesSGBPal3c1 8935
#define PlayerTilesSGBPal3c2 6596
#define PlayerTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define PlayerTilesCGBPal0c0 6076
#define PlayerTilesCGBPal0c1 8935
#define PlayerTilesCGBPal0c2 6596
#define PlayerTilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define PlayerTilesCGBPal1c0 6076
#define PlayerTilesCGBPal1c1 8935
#define PlayerTilesCGBPal1c2 6596
#define PlayerTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define PlayerTilesCGBPal2c0 6076
#define PlayerTilesCGBPal2c1 8935
#define PlayerTilesCGBPal2c2 6596
#define PlayerTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define PlayerTilesCGBPal3c0 6076
#define PlayerTilesCGBPal3c1 8935
#define PlayerTilesCGBPal3c2 6596
#define PlayerTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PlayerTilesCGBPal4c0 6076
#define PlayerTilesCGBPal4c1 8935
#define PlayerTilesCGBPal4c2 6596
#define PlayerTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PlayerTilesCGBPal5c0 6076
#define PlayerTilesCGBPal5c1 8935
#define PlayerTilesCGBPal5c2 6596
#define PlayerTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PlayerTilesCGBPal6c0 6076
#define PlayerTilesCGBPal6c1 8935
#define PlayerTilesCGBPal6c2 6596
#define PlayerTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PlayerTilesCGBPal7c0 6076
#define PlayerTilesCGBPal7c1 8935
#define PlayerTilesCGBPal7c2 6596
#define PlayerTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char PlayerTilesCGB[];
/* Start of tile array. */
extern unsigned char PlayerTiles[];

/* End of PLAYER.H */
