/*

 BUNG_M.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ermbung2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bungMapWidth 20
#define bungMapHeight 18
#define bungMapBank 0

extern unsigned char bungMap[];

/* End of BUNG_M.H */
