/*

 BUNG_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 246

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bungTilesBank 0

/* Super Gameboy palette 0 */
#define bungTilesSGBPal0c0 16976
#define bungTilesSGBPal0c1 32767
#define bungTilesSGBPal0c2 31
#define bungTilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define bungTilesSGBPal1c0 19055
#define bungTilesSGBPal1c1 21139
#define bungTilesSGBPal1c2 26393
#define bungTilesSGBPal1c3 14863

/* Super Gameboy palette 2 */
#define bungTilesSGBPal2c0 21272
#define bungTilesSGBPal2c1 9743
#define bungTilesSGBPal2c2 31711
#define bungTilesSGBPal2c3 13181

/* Super Gameboy palette 3 */
#define bungTilesSGBPal3c0 16848
#define bungTilesSGBPal3c1 20187
#define bungTilesSGBPal3c2 16750
#define bungTilesSGBPal3c3 30655

/* Gameboy Color palette 0 */
#define bungTilesCGBPal0c0 16976
#define bungTilesCGBPal0c1 32767
#define bungTilesCGBPal0c2 31
#define bungTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define bungTilesCGBPal1c0 19055
#define bungTilesCGBPal1c1 21139
#define bungTilesCGBPal1c2 26393
#define bungTilesCGBPal1c3 14863

/* Gameboy Color palette 2 */
#define bungTilesCGBPal2c0 21272
#define bungTilesCGBPal2c1 9743
#define bungTilesCGBPal2c2 31711
#define bungTilesCGBPal2c3 13181

/* Gameboy Color palette 3 */
#define bungTilesCGBPal3c0 16848
#define bungTilesCGBPal3c1 20187
#define bungTilesCGBPal3c2 16750
#define bungTilesCGBPal3c3 30655

/* Gameboy Color palette 4 */
#define bungTilesCGBPal4c0 23357
#define bungTilesCGBPal4c1 23322
#define bungTilesCGBPal4c2 21175
#define bungTilesCGBPal4c3 15889

/* Gameboy Color palette 5 */
#define bungTilesCGBPal5c0 24346
#define bungTilesCGBPal5c1 23160
#define bungTilesCGBPal5c2 32767
#define bungTilesCGBPal5c3 14902

/* Gameboy Color palette 6 */
#define bungTilesCGBPal6c0 11676
#define bungTilesCGBPal6c1 7505
#define bungTilesCGBPal6c2 19063
#define bungTilesCGBPal6c3 30686

/* Gameboy Color palette 7 */
#define bungTilesCGBPal7c0 32767
#define bungTilesCGBPal7c1 15887
#define bungTilesCGBPal7c2 19027
#define bungTilesCGBPal7c3 24279
/* CGBpalette entries. */
extern unsigned char bungTilesCGB[];
/* Start of tile array. */
extern unsigned char bungTiles[];

/* End of BUNG_T.H */
