/*

 BUNG_P.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : ermbung2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bungPalWidth 20
#define bungPalHeight 18
#define bungPalBank 0

extern unsigned char bungPal[];

/* End of BUNG_P.H */
