/*

 BUNGURL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define bungURLTilesBank 0

/* Super Gameboy palette 0 */
#define bungURLTilesSGBPal0c0 6076
#define bungURLTilesSGBPal0c1 8935
#define bungURLTilesSGBPal0c2 6596
#define bungURLTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define bungURLTilesSGBPal1c0 6076
#define bungURLTilesSGBPal1c1 8935
#define bungURLTilesSGBPal1c2 6596
#define bungURLTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define bungURLTilesSGBPal2c0 6076
#define bungURLTilesSGBPal2c1 8935
#define bungURLTilesSGBPal2c2 6596
#define bungURLTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define bungURLTilesSGBPal3c0 6076
#define bungURLTilesSGBPal3c1 8935
#define bungURLTilesSGBPal3c2 6596
#define bungURLTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define bungURLTilesCGBPal0c0 32767
#define bungURLTilesCGBPal0c1 8935
#define bungURLTilesCGBPal0c2 6596
#define bungURLTilesCGBPal0c3 31

/* Gameboy Color palette 1 */
#define bungURLTilesCGBPal1c0 6076
#define bungURLTilesCGBPal1c1 8935
#define bungURLTilesCGBPal1c2 6596
#define bungURLTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define bungURLTilesCGBPal2c0 6076
#define bungURLTilesCGBPal2c1 8935
#define bungURLTilesCGBPal2c2 6596
#define bungURLTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define bungURLTilesCGBPal3c0 6076
#define bungURLTilesCGBPal3c1 8935
#define bungURLTilesCGBPal3c2 6596
#define bungURLTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define bungURLTilesCGBPal4c0 6076
#define bungURLTilesCGBPal4c1 8935
#define bungURLTilesCGBPal4c2 6596
#define bungURLTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define bungURLTilesCGBPal5c0 6076
#define bungURLTilesCGBPal5c1 8935
#define bungURLTilesCGBPal5c2 6596
#define bungURLTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define bungURLTilesCGBPal6c0 6076
#define bungURLTilesCGBPal6c1 8935
#define bungURLTilesCGBPal6c2 6596
#define bungURLTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define bungURLTilesCGBPal7c0 6076
#define bungURLTilesCGBPal7c1 8935
#define bungURLTilesCGBPal7c2 6596
#define bungURLTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char bungURLTilesCGB[];
/* Start of tile array. */
extern unsigned char bungURLTiles[];

/* End of BUNGURL.H */
