/*

 RECORD_M.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : record.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define recordMapWidth 20
#define recordMapHeight 18
#define recordMapBank 0

extern unsigned char recordMap[];

/* End of RECORD_M.H */
