/*

 RECORD_P.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : record.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define recordPalWidth 20
#define recordPalHeight 18
#define recordPalBank 0

extern unsigned char recordPal[];

/* End of RECORD_P.H */
