/*

 RECORD_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 193

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define recordTilesBank 0

/* Super Gameboy palette 0 */
#define recordTilesSGBPal0c0 32660
#define recordTilesSGBPal0c1 17071
#define recordTilesSGBPal0c2 9379
#define recordTilesSGBPal0c3 16905

/* Super Gameboy palette 1 */
#define recordTilesSGBPal1c0 24836
#define recordTilesSGBPal1c1 12483
#define recordTilesSGBPal1c2 13659
#define recordTilesSGBPal1c3 12675

/* Super Gameboy palette 2 */
#define recordTilesSGBPal2c0 10057
#define recordTilesSGBPal2c1 29398
#define recordTilesSGBPal2c2 21240
#define recordTilesSGBPal2c3 21704

/* Super Gameboy palette 3 */
#define recordTilesSGBPal3c0 12479
#define recordTilesSGBPal3c1 0
#define recordTilesSGBPal3c2 32596
#define recordTilesSGBPal3c3 32333

/* Gameboy Color palette 0 */
#define recordTilesCGBPal0c0 32660
#define recordTilesCGBPal0c1 17071
#define recordTilesCGBPal0c2 9379
#define recordTilesCGBPal0c3 16905

/* Gameboy Color palette 1 */
#define recordTilesCGBPal1c0 24836
#define recordTilesCGBPal1c1 12483
#define recordTilesCGBPal1c2 13659
#define recordTilesCGBPal1c3 12675

/* Gameboy Color palette 2 */
#define recordTilesCGBPal2c0 10057
#define recordTilesCGBPal2c1 29398
#define recordTilesCGBPal2c2 21240
#define recordTilesCGBPal2c3 21704

/* Gameboy Color palette 3 */
#define recordTilesCGBPal3c0 12479
#define recordTilesCGBPal3c1 0
#define recordTilesCGBPal3c2 32596
#define recordTilesCGBPal3c3 32333

/* Gameboy Color palette 4 */
#define recordTilesCGBPal4c0 15313
#define recordTilesCGBPal4c1 6344
#define recordTilesCGBPal4c2 32246
#define recordTilesCGBPal4c3 29018

/* Gameboy Color palette 5 */
#define recordTilesCGBPal5c0 29940
#define recordTilesCGBPal5c1 5686
#define recordTilesCGBPal5c2 11116
#define recordTilesCGBPal5c3 2595

/* Gameboy Color palette 6 */
#define recordTilesCGBPal6c0 20593
#define recordTilesCGBPal6c1 23495
#define recordTilesCGBPal6c2 3299
#define recordTilesCGBPal6c3 20081

/* Gameboy Color palette 7 */
#define recordTilesCGBPal7c0 136
#define recordTilesCGBPal7c1 13201
#define recordTilesCGBPal7c2 17789
#define recordTilesCGBPal7c3 14211
/* CGBpalette entries. */
extern unsigned char recordTilesCGB[];
/* Start of tile array. */
extern unsigned char recordTiles[];

/* End of RECORD_T.H */
