/*

 STORY_P.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : story.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define storyPalWidth 20
#define storyPalHeight 18
#define storyPalBank 0

extern unsigned char storyPal[];

/* End of STORY_P.H */
