/*

 STORY_M.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : story.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define storyMapWidth 20
#define storyMapHeight 18
#define storyMapBank 0

extern unsigned char storyMap[];

/* End of STORY_M.H */
