/*

 STORY_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 234

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define storyTilesBank 0

/* Super Gameboy palette 0 */
#define storyTilesSGBPal0c0 1061
#define storyTilesSGBPal0c1 28051
#define storyTilesSGBPal0c2 28593
#define storyTilesSGBPal0c3 21477

/* Super Gameboy palette 1 */
#define storyTilesSGBPal1c0 14716
#define storyTilesSGBPal1c1 23157
#define storyTilesSGBPal1c2 13533
#define storyTilesSGBPal1c3 9668

/* Super Gameboy palette 2 */
#define storyTilesSGBPal2c0 14301
#define storyTilesSGBPal2c1 28729
#define storyTilesSGBPal2c2 18900
#define storyTilesSGBPal2c3 9282

/* Super Gameboy palette 3 */
#define storyTilesSGBPal3c0 18388
#define storyTilesSGBPal3c1 21559
#define storyTilesSGBPal3c2 27488
#define storyTilesSGBPal3c3 13347

/* Gameboy Color palette 0 */
#define storyTilesCGBPal0c0 1061
#define storyTilesCGBPal0c1 28051
#define storyTilesCGBPal0c2 28593
#define storyTilesCGBPal0c3 21477

/* Gameboy Color palette 1 */
#define storyTilesCGBPal1c0 14716
#define storyTilesCGBPal1c1 23157
#define storyTilesCGBPal1c2 13533
#define storyTilesCGBPal1c3 9668

/* Gameboy Color palette 2 */
#define storyTilesCGBPal2c0 14301
#define storyTilesCGBPal2c1 28729
#define storyTilesCGBPal2c2 18900
#define storyTilesCGBPal2c3 9282

/* Gameboy Color palette 3 */
#define storyTilesCGBPal3c0 18388
#define storyTilesCGBPal3c1 21559
#define storyTilesCGBPal3c2 27488
#define storyTilesCGBPal3c3 13347

/* Gameboy Color palette 4 */
#define storyTilesCGBPal4c0 6472
#define storyTilesCGBPal4c1 30735
#define storyTilesCGBPal4c2 31617
#define storyTilesCGBPal4c3 22625

/* Gameboy Color palette 5 */
#define storyTilesCGBPal5c0 13361
#define storyTilesCGBPal5c1 18116
#define storyTilesCGBPal5c2 12814
#define storyTilesCGBPal5c3 27306

/* Gameboy Color palette 6 */
#define storyTilesCGBPal6c0 31631
#define storyTilesCGBPal6c1 3984
#define storyTilesCGBPal6c2 4128
#define storyTilesCGBPal6c3 18170

/* Gameboy Color palette 7 */
#define storyTilesCGBPal7c0 26447
#define storyTilesCGBPal7c1 23971
#define storyTilesCGBPal7c2 9637
#define storyTilesCGBPal7c3 30064
/* CGBpalette entries. */
extern unsigned char storyTilesCGB[];
/* Start of tile array. */
extern unsigned char storyTiles[];

/* End of STORY_T.H */
