/*

 SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 46

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define SpriteTilesBank 0

/* Super Gameboy palette 0 */
#define SpriteTilesSGBPal0c0 30687
#define SpriteTilesSGBPal0c1 8935
#define SpriteTilesSGBPal0c2 6596
#define SpriteTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SpriteTilesSGBPal1c0 30687
#define SpriteTilesSGBPal1c1 8935
#define SpriteTilesSGBPal1c2 6596
#define SpriteTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SpriteTilesSGBPal2c0 30687
#define SpriteTilesSGBPal2c1 8935
#define SpriteTilesSGBPal2c2 6596
#define SpriteTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SpriteTilesSGBPal3c0 30687
#define SpriteTilesSGBPal3c1 8935
#define SpriteTilesSGBPal3c2 6596
#define SpriteTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SpriteTilesCGBPal0c0 6076
#define SpriteTilesCGBPal0c1 8935
#define SpriteTilesCGBPal0c2 6596
#define SpriteTilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define SpriteTilesCGBPal1c0 6076
#define SpriteTilesCGBPal1c1 8935
#define SpriteTilesCGBPal1c2 6596
#define SpriteTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define SpriteTilesCGBPal2c0 6076
#define SpriteTilesCGBPal2c1 8935
#define SpriteTilesCGBPal2c2 6596
#define SpriteTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define SpriteTilesCGBPal3c0 6076
#define SpriteTilesCGBPal3c1 8935
#define SpriteTilesCGBPal3c2 6596
#define SpriteTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define SpriteTilesCGBPal4c0 6076
#define SpriteTilesCGBPal4c1 8935
#define SpriteTilesCGBPal4c2 6596
#define SpriteTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SpriteTilesCGBPal5c0 6076
#define SpriteTilesCGBPal5c1 8935
#define SpriteTilesCGBPal5c2 6596
#define SpriteTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define SpriteTilesCGBPal6c0 6076
#define SpriteTilesCGBPal6c1 8935
#define SpriteTilesCGBPal6c2 6596
#define SpriteTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define SpriteTilesCGBPal7c0 6076
#define SpriteTilesCGBPal7c1 8935
#define SpriteTilesCGBPal7c2 6596
#define SpriteTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char SpriteTilesCGB[];
/* Start of tile array. */
extern unsigned char SpriteTiles[];

/* End of SPRITES.H */
