/*

 SPLASH_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 169

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define splashTilesBank 0

/* Super Gameboy palette 0 */
#define splashTilesSGBPal0c0 32767
#define splashTilesSGBPal0c1 0
#define splashTilesSGBPal0c2 5551
#define splashTilesSGBPal0c3 22021

/* Super Gameboy palette 1 */
#define splashTilesSGBPal1c0 19876
#define splashTilesSGBPal1c1 18784
#define splashTilesSGBPal1c2 25126
#define splashTilesSGBPal1c3 5554

/* Super Gameboy palette 2 */
#define splashTilesSGBPal2c0 6709
#define splashTilesSGBPal2c1 17651
#define splashTilesSGBPal2c2 1834
#define splashTilesSGBPal2c3 3093

/* Super Gameboy palette 3 */
#define splashTilesSGBPal3c0 8623
#define splashTilesSGBPal3c1 5717
#define splashTilesSGBPal3c2 128
#define splashTilesSGBPal3c3 27479

/* Gameboy Color palette 0 */
#define splashTilesCGBPal0c0 32767
#define splashTilesCGBPal0c1 0
#define splashTilesCGBPal0c2 5551
#define splashTilesCGBPal0c3 22021

/* Gameboy Color palette 1 */
#define splashTilesCGBPal1c0 19876
#define splashTilesCGBPal1c1 18784
#define splashTilesCGBPal1c2 25126
#define splashTilesCGBPal1c3 5554

/* Gameboy Color palette 2 */
#define splashTilesCGBPal2c0 26457
#define splashTilesCGBPal2c1 0
#define splashTilesCGBPal2c2 32767
#define splashTilesCGBPal2c3 5554

/* Gameboy Color palette 3 */
#define splashTilesCGBPal3c0 8623
#define splashTilesCGBPal3c1 5717
#define splashTilesCGBPal3c2 128
#define splashTilesCGBPal3c3 27479

/* Gameboy Color palette 4 */
#define splashTilesCGBPal4c0 0
#define splashTilesCGBPal4c1 25126
#define splashTilesCGBPal4c2 32767
#define splashTilesCGBPal4c3 5554

/* Gameboy Color palette 5 */
#define splashTilesCGBPal5c0 0
#define splashTilesCGBPal5c1 6709
#define splashTilesCGBPal5c2 32767
#define splashTilesCGBPal5c3 434

/* Gameboy Color palette 6 */
#define splashTilesCGBPal6c0 6710
#define splashTilesCGBPal6c1 0
#define splashTilesCGBPal6c2 6578
#define splashTilesCGBPal6c3 27481

/* Gameboy Color palette 7 */
#define splashTilesCGBPal7c0 26457
#define splashTilesCGBPal7c1 0
#define splashTilesCGBPal7c2 32767
#define splashTilesCGBPal7c3 6709
/* CGBpalette entries. */
extern unsigned char splashTilesCGB[];
/* Start of tile array. */
extern unsigned char splashTiles[];

/* End of SPLASH_T.H */
