/*

 SPLASH_P.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : splash.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define splashPalWidth 20
#define splashPalHeight 18
#define splashPalBank 0

extern unsigned char splashPal[];

/* End of SPLASH_P.H */
