/*

 MENU_P.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : mainmenu.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menuPalWidth 20
#define menuPalHeight 18
#define menuPalBank 0

extern unsigned char menuPal[];

/* End of MENU_P.H */
