/*

 MENU_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 140

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define menuTilesBank 0

/* Super Gameboy palette 0 */
#define menuTilesSGBPal0c0 32767
#define menuTilesSGBPal0c1 31571
#define menuTilesSGBPal0c2 31865
#define menuTilesSGBPal0c3 0

/* Super Gameboy palette 1 */
#define menuTilesSGBPal1c0 0
#define menuTilesSGBPal1c1 31571
#define menuTilesSGBPal1c2 0
#define menuTilesSGBPal1c3 0

/* Super Gameboy palette 2 */
#define menuTilesSGBPal2c0 0
#define menuTilesSGBPal2c1 31571
#define menuTilesSGBPal2c2 0
#define menuTilesSGBPal2c3 0

/* Super Gameboy palette 3 */
#define menuTilesSGBPal3c0 0
#define menuTilesSGBPal3c1 31571
#define menuTilesSGBPal3c2 0
#define menuTilesSGBPal3c3 0

/* Gameboy Color palette 0 */
#define menuTilesCGBPal0c0 32767
#define menuTilesCGBPal0c1 31571
#define menuTilesCGBPal0c2 31865
#define menuTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define menuTilesCGBPal1c0 0
#define menuTilesCGBPal1c1 31571
#define menuTilesCGBPal1c2 0
#define menuTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define menuTilesCGBPal2c0 0
#define menuTilesCGBPal2c1 31571
#define menuTilesCGBPal2c2 0
#define menuTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define menuTilesCGBPal3c0 0
#define menuTilesCGBPal3c1 31571
#define menuTilesCGBPal3c2 0
#define menuTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define menuTilesCGBPal4c0 0
#define menuTilesCGBPal4c1 31571
#define menuTilesCGBPal4c2 0
#define menuTilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define menuTilesCGBPal5c0 0
#define menuTilesCGBPal5c1 31571
#define menuTilesCGBPal5c2 0
#define menuTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define menuTilesCGBPal6c0 0
#define menuTilesCGBPal6c1 31571
#define menuTilesCGBPal6c2 0
#define menuTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define menuTilesCGBPal7c0 0
#define menuTilesCGBPal7c1 31571
#define menuTilesCGBPal7c2 0
#define menuTilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char menuTilesCGB[];
/* Start of tile array. */
extern unsigned char menuTiles[];

/* End of MENU_T.H */
