/*

 POINTER.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define pointerTilesBank 0

/* Super Gameboy palette 0 */
#define pointerTilesSGBPal0c0 6076
#define pointerTilesSGBPal0c1 8935
#define pointerTilesSGBPal0c2 6596
#define pointerTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define pointerTilesSGBPal1c0 6076
#define pointerTilesSGBPal1c1 8935
#define pointerTilesSGBPal1c2 6596
#define pointerTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pointerTilesSGBPal2c0 6076
#define pointerTilesSGBPal2c1 8935
#define pointerTilesSGBPal2c2 6596
#define pointerTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pointerTilesSGBPal3c0 6076
#define pointerTilesSGBPal3c1 8935
#define pointerTilesSGBPal3c2 6596
#define pointerTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pointerTilesCGBPal0c0 27424
#define pointerTilesCGBPal0c1 20919
#define pointerTilesCGBPal0c2 31865
#define pointerTilesCGBPal0c3 32767

/* Gameboy Color palette 1 */
#define pointerTilesCGBPal1c0 27424
#define pointerTilesCGBPal1c1 401
#define pointerTilesCGBPal1c2 495
#define pointerTilesCGBPal1c3 23936

/* Gameboy Color palette 2 */
#define pointerTilesCGBPal2c0 6076
#define pointerTilesCGBPal2c1 8935
#define pointerTilesCGBPal2c2 6596
#define pointerTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define pointerTilesCGBPal3c0 6076
#define pointerTilesCGBPal3c1 8935
#define pointerTilesCGBPal3c2 6596
#define pointerTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define pointerTilesCGBPal4c0 6076
#define pointerTilesCGBPal4c1 8935
#define pointerTilesCGBPal4c2 6596
#define pointerTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define pointerTilesCGBPal5c0 6076
#define pointerTilesCGBPal5c1 8935
#define pointerTilesCGBPal5c2 6596
#define pointerTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define pointerTilesCGBPal6c0 6076
#define pointerTilesCGBPal6c1 8935
#define pointerTilesCGBPal6c2 6596
#define pointerTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define pointerTilesCGBPal7c0 6076
#define pointerTilesCGBPal7c1 8935
#define pointerTilesCGBPal7c2 6596
#define pointerTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char pointerTilesCGB[];
/* Start of tile array. */
extern unsigned char pointerTiles[];

/* End of POINTER.H */
