/*

 BACK_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 49

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define backTilesBank 0

/* Super Gameboy palette 0 */
#define backTilesSGBPal0c0 25350
#define backTilesSGBPal0c1 9616
#define backTilesSGBPal0c2 6391
#define backTilesSGBPal0c3 30504

/* Super Gameboy palette 1 */
#define backTilesSGBPal1c0 22889
#define backTilesSGBPal1c1 25912
#define backTilesSGBPal1c2 1902
#define backTilesSGBPal1c3 24456

/* Super Gameboy palette 2 */
#define backTilesSGBPal2c0 4576
#define backTilesSGBPal2c1 1697
#define backTilesSGBPal2c2 32484
#define backTilesSGBPal2c3 1088

/* Super Gameboy palette 3 */
#define backTilesSGBPal3c0 25330
#define backTilesSGBPal3c1 3977
#define backTilesSGBPal3c2 32736
#define backTilesSGBPal3c3 29672

/* Gameboy Color palette 0 */
#define backTilesCGBPal0c0 32767
#define backTilesCGBPal0c1 31
#define backTilesCGBPal0c2 31744
#define backTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define backTilesCGBPal1c0 22889
#define backTilesCGBPal1c1 25912
#define backTilesCGBPal1c2 1902
#define backTilesCGBPal1c3 24456

/* Gameboy Color palette 2 */
#define backTilesCGBPal2c0 4576
#define backTilesCGBPal2c1 1697
#define backTilesCGBPal2c2 32484
#define backTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define backTilesCGBPal3c0 25330
#define backTilesCGBPal3c1 3977
#define backTilesCGBPal3c2 32736
#define backTilesCGBPal3c3 29672

/* Gameboy Color palette 4 */
#define backTilesCGBPal4c0 3392
#define backTilesCGBPal4c1 4576
#define backTilesCGBPal4c2 2933
#define backTilesCGBPal4c3 19991

/* Gameboy Color palette 5 */
#define backTilesCGBPal5c0 128
#define backTilesCGBPal5c1 1697
#define backTilesCGBPal5c2 3392
#define backTilesCGBPal5c3 25696

/* Gameboy Color palette 6 */
#define backTilesCGBPal6c0 2912
#define backTilesCGBPal6c1 17011
#define backTilesCGBPal6c2 8080
#define backTilesCGBPal6c3 17553

/* Gameboy Color palette 7 */
#define backTilesCGBPal7c0 4576
#define backTilesCGBPal7c1 0
#define backTilesCGBPal7c2 3392
#define backTilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char backTilesCGB[];
/* Start of tile array. */
extern unsigned char backTiles[];

/* End of BACK_T.H */
