/*

 GAME_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 21

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define gameTilesBank 0

/* Super Gameboy palette 0 */
#define gameTilesSGBPal0c0 6076
#define gameTilesSGBPal0c1 8935
#define gameTilesSGBPal0c2 6596
#define gameTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define gameTilesSGBPal1c0 6076
#define gameTilesSGBPal1c1 8935
#define gameTilesSGBPal1c2 6596
#define gameTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define gameTilesSGBPal2c0 6076
#define gameTilesSGBPal2c1 8935
#define gameTilesSGBPal2c2 6596
#define gameTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define gameTilesSGBPal3c0 6076
#define gameTilesSGBPal3c1 8935
#define gameTilesSGBPal3c2 6596
#define gameTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define gameTilesCGBPal0c0 31476
#define gameTilesCGBPal0c1 15904
#define gameTilesCGBPal0c2 3935
#define gameTilesCGBPal0c3 21140

/* Gameboy Color palette 1 */
#define gameTilesCGBPal1c0 31749
#define gameTilesCGBPal1c1 32767
#define gameTilesCGBPal1c2 15855
#define gameTilesCGBPal1c3 21140

/* Gameboy Color palette 2 */
#define gameTilesCGBPal2c0 8209
#define gameTilesCGBPal2c1 465
#define gameTilesCGBPal2c2 4086
#define gameTilesCGBPal2c3 5249

/* Gameboy Color palette 3 */
#define gameTilesCGBPal3c0 26644
#define gameTilesCGBPal3c1 32767
#define gameTilesCGBPal3c2 31
#define gameTilesCGBPal3c3 2688

/* Gameboy Color palette 4 */
#define gameTilesCGBPal4c0 0
#define gameTilesCGBPal4c1 27551
#define gameTilesCGBPal4c2 16089
#define gameTilesCGBPal4c3 729

/* Gameboy Color palette 5 */
#define gameTilesCGBPal5c0 26644
#define gameTilesCGBPal5c1 32767
#define gameTilesCGBPal5c2 31
#define gameTilesCGBPal5c3 957

/* Gameboy Color palette 6 */
#define gameTilesCGBPal6c0 31749
#define gameTilesCGBPal6c1 32767
#define gameTilesCGBPal6c2 15855
#define gameTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define gameTilesCGBPal7c0 26650
#define gameTilesCGBPal7c1 1023
#define gameTilesCGBPal7c2 32767
#define gameTilesCGBPal7c3 165
/* CGBpalette entries. */
extern unsigned char gameTilesCGB[];
/* Start of tile array. */
extern unsigned char gameTiles[];

/* End of GAME_T.H */
