/*

 INFOW_P.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 18
   Tile set      : infoWin.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define infoWinPalWidth 4
#define infoWinPalHeight 18
#define infoWinPalBank 0

extern unsigned char infoWinPal[];

/* End of INFOW_P.H */
