/*

 INFOW_M.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 18
   Tile set      : infoWin.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define infoWinMapWidth 4
#define infoWinMapHeight 18
#define infoWinMapBank 0

extern unsigned char infoWinMap[];

/* End of INFOW_M.H */
