/*

 INFOW_T.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 58

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define infoWinTilesBank 0

/* Super Gameboy palette 0 */
#define infoWinTilesSGBPal0c0 25350
#define infoWinTilesSGBPal0c1 9616
#define infoWinTilesSGBPal0c2 6391
#define infoWinTilesSGBPal0c3 30504

/* Super Gameboy palette 1 */
#define infoWinTilesSGBPal1c0 22889
#define infoWinTilesSGBPal1c1 25912
#define infoWinTilesSGBPal1c2 1902
#define infoWinTilesSGBPal1c3 24456

/* Super Gameboy palette 2 */
#define infoWinTilesSGBPal2c0 4576
#define infoWinTilesSGBPal2c1 1697
#define infoWinTilesSGBPal2c2 32484
#define infoWinTilesSGBPal2c3 1088

/* Super Gameboy palette 3 */
#define infoWinTilesSGBPal3c0 25330
#define infoWinTilesSGBPal3c1 3977
#define infoWinTilesSGBPal3c2 32736
#define infoWinTilesSGBPal3c3 29672

/* Gameboy Color palette 0 */
#define infoWinTilesCGBPal0c0 32767
#define infoWinTilesCGBPal0c1 31
#define infoWinTilesCGBPal0c2 31744
#define infoWinTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define infoWinTilesCGBPal1c0 22889
#define infoWinTilesCGBPal1c1 25912
#define infoWinTilesCGBPal1c2 1902
#define infoWinTilesCGBPal1c3 24456

/* Gameboy Color palette 2 */
#define infoWinTilesCGBPal2c0 4576
#define infoWinTilesCGBPal2c1 1697
#define infoWinTilesCGBPal2c2 32484
#define infoWinTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define infoWinTilesCGBPal3c0 25330
#define infoWinTilesCGBPal3c1 3977
#define infoWinTilesCGBPal3c2 32736
#define infoWinTilesCGBPal3c3 29672

/* Gameboy Color palette 4 */
#define infoWinTilesCGBPal4c0 3392
#define infoWinTilesCGBPal4c1 4576
#define infoWinTilesCGBPal4c2 2933
#define infoWinTilesCGBPal4c3 19991

/* Gameboy Color palette 5 */
#define infoWinTilesCGBPal5c0 128
#define infoWinTilesCGBPal5c1 1697
#define infoWinTilesCGBPal5c2 3392
#define infoWinTilesCGBPal5c3 25696

/* Gameboy Color palette 6 */
#define infoWinTilesCGBPal6c0 2912
#define infoWinTilesCGBPal6c1 17011
#define infoWinTilesCGBPal6c2 8080
#define infoWinTilesCGBPal6c3 17553

/* Gameboy Color palette 7 */
#define infoWinTilesCGBPal7c0 4576
#define infoWinTilesCGBPal7c1 0
#define infoWinTilesCGBPal7c2 3392
#define infoWinTilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char infoWinTilesCGB[];
/* Start of tile array. */
extern unsigned char infoWinTiles[];

/* End of INFOW_T.H */
