/*

 BULLETTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 4

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BulletTilesBank 0

/* Super Gameboy palette 0 */
#define BulletTilesSGBPal0c0 30687
#define BulletTilesSGBPal0c1 8935
#define BulletTilesSGBPal0c2 6596
#define BulletTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BulletTilesSGBPal1c0 30687
#define BulletTilesSGBPal1c1 8935
#define BulletTilesSGBPal1c2 6596
#define BulletTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BulletTilesSGBPal2c0 30687
#define BulletTilesSGBPal2c1 8935
#define BulletTilesSGBPal2c2 6596
#define BulletTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BulletTilesSGBPal3c0 30687
#define BulletTilesSGBPal3c1 8935
#define BulletTilesSGBPal3c2 6596
#define BulletTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BulletTilesCGBPal0c0 6076
#define BulletTilesCGBPal0c1 8935
#define BulletTilesCGBPal0c2 6596
#define BulletTilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define BulletTilesCGBPal1c0 6076
#define BulletTilesCGBPal1c1 8935
#define BulletTilesCGBPal1c2 6596
#define BulletTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define BulletTilesCGBPal2c0 6076
#define BulletTilesCGBPal2c1 8935
#define BulletTilesCGBPal2c2 6596
#define BulletTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define BulletTilesCGBPal3c0 6076
#define BulletTilesCGBPal3c1 8935
#define BulletTilesCGBPal3c2 6596
#define BulletTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BulletTilesCGBPal4c0 6076
#define BulletTilesCGBPal4c1 8935
#define BulletTilesCGBPal4c2 6596
#define BulletTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BulletTilesCGBPal5c0 6076
#define BulletTilesCGBPal5c1 8935
#define BulletTilesCGBPal5c2 6596
#define BulletTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BulletTilesCGBPal6c0 6076
#define BulletTilesCGBPal6c1 8935
#define BulletTilesCGBPal6c2 6596
#define BulletTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BulletTilesCGBPal7c0 6076
#define BulletTilesCGBPal7c1 8935
#define BulletTilesCGBPal7c2 6596
#define BulletTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char BulletTilesCGB[];
/* Start of tile array. */
extern unsigned char BulletTiles[];

/* End of BULLETTILES.H */
