/*

 BACKGROUNDMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : C:\Users\Perma_000\Documents\GBJAM\source\graphics\background\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapWidth 10
#define BackgroundMapHeight 10
#define BackgroundMapBank 0

extern unsigned char BackgroundMap[];

/* End of BACKGROUNDMAP.H */
