/*

 BACKGROUND.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
unsigned char BackgroundTilesCGB[] =
{
  0x00,0x00
};
/* Start of tile array. */
unsigned char BackgroundTiles[] =
{
  0x00,0x00,0x03,0x00,0x70,0x00,0x00,0x00,
  0xC0,0x00,0x02,0x00,0xC7,0x00,0x70,0x00,
  0x00,0x00,0x03,0x00,0x70,0x00,0x00,0x00,
  0xC0,0x00,0x02,0x00,0xC7,0x00,0x70,0x00
};

/* End of BACKGROUND.C */
