/*

 BACKGROUNDMAPCOLLIDERS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 25 x 27
   Tile set      : C:\Users\Perma_000\Documents\GBJAM\source\graphics\background\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundMapCollidersWidth 25
#define BackgroundMapCollidersHeight 27
#define BackgroundMapCollidersBank 0

extern unsigned char BackgroundMapColliders[];

/* End of BACKGROUNDMAPCOLLIDERS.H */
